#!/usr/bin/python
import cgi
import string

# Return the contents of members.csv as list of lines
# Get rid of whitespace from the start and end of each line
def readMembersFile():
        lines = []
        f = open("members.csv", 'r')
        for line in f:
                lines.append(line.strip())
        f.close()
        return lines

# Return the list of names of registered users
def getRegisteredUsers():
        users = []
        for line in readMembersFile():
                words = line.split(" ")
                if len(words) < 2:
                		continue
                users.append(words[1])
        return users

# Return the list of friends for username
def getFriends(username):
        friends = []
        for line in readMembersFile():
                words = line.split(" ")
                if words[1] == username:
                        friends = words[3:]
                        break
        return friends

# Add friendname as a friend for username and update members.csv
# Only add the friend if friendname is the name of a registered user
# Only add the friend if not already a friend for username
def addFriend(username, friendname):
        doUpdate = False
        users = getRegisteredUsers()
        
        # Only add friend if friendname matches a registered user
        if friendname in users:
                # get the current friends for username
                friends = getFriends(username)
                
                # only add friendname if not already a friend
                if not friendname in friends:
                        # add new friend to the list of friends
                        friends.append(friendname)
                        
                        # indicate that members.csv needs to be updated
                        doUpdate = True
        
        if doUpdate:
                # need to update the members file
                lines = readMembersFile()
                f = open("members.csv", "w")
                for line in lines:
                        words = line.split(" ")
                        if len(words) < 2 :
                				continue
                        if words[1] == username:
                                # write updated entry
                                f.write("%s %s %s %s\n" % (words[0], words[1], words[2], " ".join(friends)))
                        else:
                                # copy existing entry
                                f.write("%s\n" % line)
                f.close()

# Return the contents of topic.csv as list of lines
# Get rid of whitespace from the start and end of each line
def readtopicsfile():
        lines = []
        f = open("topic.csv", 'r')
        for line in f:
                lines.append(line.strip())
        f.close()
        return lines

# return the 10 most recent friends' posts
def getFriendsPosts(username):
		posts = []
		friends = getFriends(username)
		f = readtopicsfile()
		i = 0
		while (i+1) < len(f) :
				user = f[i]
				if user in friends :
						status = "%s: %s" % (f[i], f[i+1])
						posts.append(status)
				i = i + 2
		return posts[-10:]

#add a post to the topic.csv file
def addPost(username, post):
		f = open("topic.csv", "a")
		f.write("%s\n" % username)
		f.write("%s\n" % post)
		f.close()

form = cgi.FieldStorage()
action = form.getvalue("action")
username = form.getvalue("username")

#if new update posted reload page with new topic
if action == "postupdate":
	topic  = form.getvalue("topic")
	addPost(username, topic)
#if new friend added reload page with friends posts
elif action == "addfriend" :
	friend = form.getvalue("friend")
	addFriend(username, friend)

print "Content-type: text/html\n\n"
print """
<!DOCTYPE html>
<html lang="en">
	<img src="http://cgi.cs.mcgill.ca/~hpurdi/ApartmentHunt/logo.png" width="50" height="50" alt="House Logo"> 
	<title>MTL Apartment Hunt</title>
	</head>
<body style ="background-color:black">
"""
# adds username to title of topics page
print "<h1><font color=\"#FFFFFF\"> %s, Welcome to MTL Apartment Hunt! </font></h1>" % (username)
print """	
	<form action="http://cgi.cs.mcgill.ca/~hpurdi/ApartmentHunt/cgi-bin/MyFacebookPage.py" method="POST">
	<br>
	<font color="#FFFFFF">Write Post:</font><br>
	<input type="text" size="25" name="topic">
	<br>
	<input type="hidden" name="action" value="postupdate">"""
#hidden username form to pass username to next html page generated by this python script
print "<input type=\"hidden\" name=\"username\" value=\"%s\">" % (username)
print """
	<input type="submit" value="Post">
	</form>
	<br>
	<br>
	<table>
	<th><td><font color="#FFFFFF"> Ten most recent posts </font></td></th> """
# prints all posts from friends in html table element
for line in getFriendsPosts(username):
        print	"<tr><td><font color=\"#FFFFFF\"> %s </font></td></tr>\n" % (line)
print	""" 
	</table>
	<br>
	<br>
	<form>
	<font color="#FFFFFF">Add Friend:</font><br>
	<input type="text" size="25" name="friend">
	<br>
	<input type="hidden" name="action" value="addfriend">"""
#hidden username form to pass username to next html page generated by this python script
print "<input type=\"hidden\" name=\"username\" value=\"%s\">" % (username)
print """
	<input type="submit" value="Add">
	</form>
	<br>
	<br>
	<table>
	<th><td><font color="#FFFFFF"> Current Members: </font></td></th> """
#print all current members in html table element
for user in getRegisteredUsers():
		print "<tr><td><font color=\"#FFFFFF\"> %s </font></td></tr>\n" % (user)
print	""" 
	</table>
	<br>
	<p><a href="http://cgi.cs.mcgill.ca/~hpurdi/ApartmentHunt/welcome.html">Logout and Return to Home Page</a></p>
	<p><small><font color="#808080"> &copy Coco&SkushLtd</font></small></p>
	</body>
	</html>
"""